# Generated by Django 4.1.7 on 2023-03-15 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="comment", new_name="comment_content",
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.post",
            ),
        ),
    ]
